[workspace]
resolver = "2"
members = [
    #
    'build',
    'packages/lib-web/build/',
    'packages/lib-web/lib/',
    'packages/lib-node/build',
    'packages/lib-node/lib',
]

[metadata.wasm-pack.profile.release]
wasm-opt = [ '-Os' ]
